import { writeFile, readFile } from "./vibeCodingClient";
import {
  LEGACY_PLAN_DOCUMENT_REL_PATH,
  PLAN_DOCUMENTS_DIR,
  resolvePlanDocumentRelPath,
} from "../../shared/planFilePath";
import { looksLikeModificationPlan } from "./agentContinuation";
import { looksLikeClarificationQuestion } from "../orchestration/generic/ambiguousTermTriggers";
import { looksLikeStreamingPlanContent } from "./planDocumentDisplay";
import { stripToolSummaryFromAssistantContent, type ChatMessage } from "./vibeChatStorage";

/** Legacy shared plan path; new plans use {@link PLAN_DOCUMENTS_DIR}/&lt;messageId&gt;.md. */
export const PLAN_FILE_REL_PATH = LEGACY_PLAN_DOCUMENT_REL_PATH;

export {
  PLAN_DOCUMENTS_DIR,
  buildPlanDocumentRelPath,
  resolvePlanDocumentRelPath,
  isPlanDocumentPath,
} from "../../shared/planFilePath";

const PLAN_FILE_PREAMBLE_RE = /^<!--\s*agent-plan-file[\s\S]*?-->\s*/i;

export function stripPlanFilePreamble(raw: string): string {
  return raw.replace(PLAN_FILE_PREAMBLE_RE, "").trim();
}

export function buildPlanFileDocument(planMarkdown: string): string {
  const body = planMarkdown.trim();
  if (!body) return "";
  return [
    "<!-- agent-plan-file: generated by AIALL Plan mode; edit before 执行方案 -->",
    "",
    body,
    "",
  ].join("\n");
}

export async function persistPlanFile(
  projectPath: string,
  planMarkdown: string,
  planFileRelPath: string,
): Promise<{ ok: boolean; path: string; error?: string }> {
  const root = projectPath.trim();
  const relPath = planFileRelPath.replace(/\\/g, "/").trim();
  if (!root) return { ok: false, path: relPath, error: "项目未打开" };
  if (!relPath) return { ok: false, path: relPath, error: "方案路径无效" };
  const document = buildPlanFileDocument(planMarkdown);
  if (!document) return { ok: false, path: relPath, error: "方案正文为空" };
  const result = await writeFile(relPath, document, root);
  if (!result.ok) {
    return { ok: false, path: relPath, error: result.error || "写入失败" };
  }
  return { ok: true, path: relPath };
}

export async function readPlanFile(
  projectPath: string,
  planFileRelPath: string,
): Promise<{ ok: boolean; content?: string; error?: string }> {
  const root = projectPath.trim();
  const relPath = planFileRelPath.replace(/\\/g, "/").trim();
  if (!root) return { ok: false, error: "项目未打开" };
  if (!relPath) return { ok: false, error: "方案路径无效" };
  const result = await readFile(relPath, root);
  if (!result.ok) return { ok: false, error: result.error };
  const content = stripPlanFilePreamble(result.content || "");
  if (!content) return { ok: false, error: "方案文件为空" };
  return { ok: true, content };
}

/** Prefer on-disk plan file (user may have edited) over chat bubble text. */
export async function resolvePlanContentForExecution(
  projectPath: string,
  messageFallback: string,
  planFileRelPath: string,
): Promise<string> {
  const disk = await readPlanFile(projectPath, planFileRelPath);
  if (disk.ok && disk.content?.trim()) return disk.content;
  return messageFallback.trim();
}

export type EnsurePlanFileBeforeExecutionResult = {
  planContent: string;
  planFilePath?: string;
  persistError?: string;
};

async function tryReadLegacySharedPlan(
  projectPath: string,
  existingPlanFilePath: string | undefined,
): Promise<string | undefined> {
  if (existingPlanFilePath?.replace(/\\/g, "/").trim() !== LEGACY_PLAN_DOCUMENT_REL_PATH) {
    return undefined;
  }
  const legacy = await readPlanFile(projectPath, LEGACY_PLAN_DOCUMENT_REL_PATH);
  return legacy.ok && legacy.content?.trim() ? legacy.content : undefined;
}

/** Persist plan when missing, then resolve execution content (disk preferred). */
export async function ensurePlanFileBeforeExecution(
  projectPath: string,
  planMarkdown: string,
  messageId: string,
  existingPlanFilePath?: string,
): Promise<EnsurePlanFileBeforeExecutionResult> {
  const root = projectPath.trim();
  const fallback = planMarkdown.trim();
  const mid = messageId.trim();
  if (!root || !mid) return { planContent: fallback };

  const targetPath = resolvePlanDocumentRelPath(mid, existingPlanFilePath);
  const disk = await readPlanFile(root, targetPath);
  if (disk.ok && disk.content?.trim()) {
    return { planContent: disk.content, planFilePath: targetPath };
  }

  const legacyContent = await tryReadLegacySharedPlan(root, existingPlanFilePath);
  if (legacyContent) {
    const migrated = await persistPlanFile(root, legacyContent, targetPath);
    if (migrated.ok) {
      return { planContent: legacyContent, planFilePath: targetPath };
    }
    return { planContent: legacyContent, planFilePath: targetPath };
  }

  const shouldPersist =
    Boolean(fallback)
    && (looksLikeModificationPlan(fallback) || Boolean(existingPlanFilePath?.trim()));
  if (!shouldPersist) {
    return { planContent: fallback, planFilePath: targetPath };
  }

  const saved = await persistPlanFile(root, fallback, targetPath);
  if (!saved.ok) {
    return {
      planContent: fallback,
      planFilePath: targetPath,
      persistError: saved.error || "写入失败",
    };
  }

  const planContent = await resolvePlanContentForExecution(root, fallback, targetPath);
  return { planContent, planFilePath: targetPath };
}

type PlanMessageSource = Pick<
  ChatMessage,
  "id" | "content" | "roundGroups" | "planFilePath" | "chatMode"
>;

/** Recover plan markdown from persisted assistant message fields (post-refresh). */
export function extractPlanContentFromStoredMessage(
  msg: PlanMessageSource,
  displayedContent = "",
): string {
  const displayed = displayedContent.trim();
  if (displayed && (looksLikeModificationPlan(displayed) || looksLikeStreamingPlanContent(displayed))) {
    return displayed;
  }

  const finalGroups = msg.roundGroups?.filter((group) => group.response?.isFinal) ?? [];
  for (let i = finalGroups.length - 1; i >= 0; i -= 1) {
    const fromRound = stripToolSummaryFromAssistantContent(
      finalGroups[i]?.response?.assistantText || "",
    ).trim();
    if (fromRound) return fromRound;
  }

  const raw = stripToolSummaryFromAssistantContent(msg.content || "").trim();
  if (!raw || raw.startsWith("[Agent 运行失败]") || raw.startsWith("运行中断")) {
    return displayed;
  }
  if (looksLikeModificationPlan(raw) || looksLikeStreamingPlanContent(raw) || msg.planFilePath) {
    return raw;
  }
  return displayed || raw;
}

/** Clarification-only Plan replies stay in chat (options), not the left plan panel. */
export function isPlanClarificationOnly(content: string): boolean {
  return looksLikeClarificationQuestion(content);
}

/** Plan-mode chat teaser vs inline markdown + selectable options. */
export function shouldUsePlanExternalView(
  content: string,
  msg: Pick<ChatMessage, "chatMode">,
): boolean {
  if (msg.chatMode !== "plan") return false;
  return !isPlanClarificationOnly(content);
}

export function messageQualifiesForPlanPanel(
  content: string,
  msg: Pick<ChatMessage, "planFilePath" | "chatMode">,
): boolean {
  if (msg.chatMode !== "plan") return false;
  if (isPlanClarificationOnly(content)) return false;
  if (msg.planFilePath?.trim()) return true;
  const text = content.trim();
  if (!text) return false;
  return looksLikeStreamingPlanContent(text) || looksLikeModificationPlan(text);
}

/** Whether an in-flight or completed plan message should drive the left plan panel. */
export function qualifiesPlanPanelSync(
  content: string,
  msg: Pick<ChatMessage, "planFilePath" | "chatMode">,
  isRunning: boolean,
): boolean {
  if (isPlanClarificationOnly(content)) return false;
  return (
    messageQualifiesForPlanPanel(content, msg)
    || (isRunning && msg.chatMode === "plan" && looksLikeStreamingPlanContent(content.trim()))
  );
}

/** User explicitly opened the plan panel — allow any non-empty Plan-mode answer. */
export function canForceOpenPlanPanel(
  content: string,
  msg: Pick<ChatMessage, "chatMode">,
): boolean {
  if (msg.chatMode !== "plan" || !content.trim()) return false;
  return !isPlanClarificationOnly(content);
}

export async function resolvePlanContentForDisplay(
  projectPath: string,
  msg: PlanMessageSource,
  displayedContent = "",
): Promise<string> {
  const inline = extractPlanContentFromStoredMessage(msg, displayedContent).trim();
  if (inline && messageQualifiesForPlanPanel(inline, msg)) return inline;
  if (msg.chatMode === "plan" && inline) return inline;
  const root = projectPath.trim();
  const targetPath = msg.id
    ? resolvePlanDocumentRelPath(msg.id, msg.planFilePath)
    : msg.planFilePath?.trim();
  if (root && targetPath) {
    const disk = await readPlanFile(root, targetPath);
    if (disk.ok && disk.content?.trim()) return disk.content.trim();
    if (
      inline
      && msg.id
      && (looksLikeModificationPlan(inline) || looksLikeStreamingPlanContent(inline))
    ) {
      const saved = await persistPlanFile(root, inline, targetPath);
      if (saved.ok) {
        const retry = await readPlanFile(root, targetPath);
        if (retry.ok && retry.content?.trim()) return retry.content.trim();
      }
    }
  }
  return inline;
}
