import { writeFile, readFile } from "./vibeCodingClient";
import { looksLikeModificationPlan } from "./agentContinuation";
import { looksLikeClarificationQuestion } from "../orchestration/generic/ambiguousTermTriggers";
import { looksLikeStreamingPlanContent } from "./planDocumentDisplay";
import { stripToolSummaryFromAssistantContent, type ChatMessage } from "./vibeChatStorage";

/** Canonical on-disk plan document (under project `.aiall/`). */
export const PLAN_FILE_REL_PATH = ".aiall/PLAN.md";

const PLAN_FILE_PREAMBLE_RE = /^<!--\s*agent-plan-file[\s\S]*?-->\s*/i;

export function stripPlanFilePreamble(raw: string): string {
  return raw.replace(PLAN_FILE_PREAMBLE_RE, "").trim();
}

export function buildPlanFileDocument(planMarkdown: string): string {
  const body = planMarkdown.trim();
  if (!body) return "";
  return [
    "<!-- agent-plan-file: generated by AIALL Plan mode; edit before 执行方案 -->",
    "",
    body,
    "",
  ].join("\n");
}

export async function persistPlanFile(
  projectPath: string,
  planMarkdown: string,
): Promise<{ ok: boolean; path: string; error?: string }> {
  const root = projectPath.trim();
  if (!root) return { ok: false, path: PLAN_FILE_REL_PATH, error: "项目未打开" };
  const document = buildPlanFileDocument(planMarkdown);
  if (!document) return { ok: false, path: PLAN_FILE_REL_PATH, error: "方案正文为空" };
  const result = await writeFile(PLAN_FILE_REL_PATH, document, root);
  if (!result.ok) {
    return { ok: false, path: PLAN_FILE_REL_PATH, error: result.error || "写入失败" };
  }
  return { ok: true, path: PLAN_FILE_REL_PATH };
}

export async function readPlanFile(
  projectPath: string,
): Promise<{ ok: boolean; content?: string; error?: string }> {
  const root = projectPath.trim();
  if (!root) return { ok: false, error: "项目未打开" };
  const result = await readFile(PLAN_FILE_REL_PATH, root);
  if (!result.ok) return { ok: false, error: result.error };
  const content = stripPlanFilePreamble(result.content || "");
  if (!content) return { ok: false, error: "方案文件为空" };
  return { ok: true, content };
}

/** Prefer on-disk PLAN.md (user may have edited) over chat bubble text. */
export async function resolvePlanContentForExecution(
  projectPath: string,
  messageFallback: string,
): Promise<string> {
  const disk = await readPlanFile(projectPath);
  if (disk.ok && disk.content?.trim()) return disk.content;
  return messageFallback.trim();
}

type PlanMessageSource = Pick<ChatMessage, "content" | "roundGroups" | "planFilePath" | "chatMode">;

/** Recover plan markdown from persisted assistant message fields (post-refresh). */
export function extractPlanContentFromStoredMessage(
  msg: PlanMessageSource,
  displayedContent = "",
): string {
  const displayed = displayedContent.trim();
  if (displayed && (looksLikeModificationPlan(displayed) || looksLikeStreamingPlanContent(displayed))) {
    return displayed;
  }

  const finalGroups = msg.roundGroups?.filter((group) => group.response?.isFinal) ?? [];
  for (let i = finalGroups.length - 1; i >= 0; i -= 1) {
    const fromRound = stripToolSummaryFromAssistantContent(
      finalGroups[i]?.response?.assistantText || "",
    ).trim();
    if (fromRound) return fromRound;
  }

  const raw = stripToolSummaryFromAssistantContent(msg.content || "").trim();
  if (!raw || raw.startsWith("[Agent 运行失败]") || raw.startsWith("运行中断")) {
    return displayed;
  }
  if (looksLikeModificationPlan(raw) || looksLikeStreamingPlanContent(raw) || msg.planFilePath) {
    return raw;
  }
  return displayed || raw;
}

/** Clarification-only Plan replies stay in chat (options), not the left plan panel. */
export function isPlanClarificationOnly(content: string): boolean {
  return looksLikeClarificationQuestion(content);
}

/** Plan-mode chat teaser vs inline markdown + selectable options. */
export function shouldUsePlanExternalView(
  content: string,
  msg: Pick<ChatMessage, "chatMode">,
): boolean {
  if (msg.chatMode !== "plan") return false;
  return !isPlanClarificationOnly(content);
}

export function messageQualifiesForPlanPanel(
  content: string,
  msg: Pick<ChatMessage, "planFilePath" | "chatMode">,
): boolean {
  if (msg.chatMode !== "plan") return false;
  if (isPlanClarificationOnly(content)) return false;
  if (msg.planFilePath?.trim()) return true;
  const text = content.trim();
  if (!text) return false;
  return looksLikeStreamingPlanContent(text) || looksLikeModificationPlan(text);
}

/** Whether an in-flight or completed plan message should drive the left plan panel. */
export function qualifiesPlanPanelSync(
  content: string,
  msg: Pick<ChatMessage, "planFilePath" | "chatMode">,
  isRunning: boolean,
): boolean {
  if (isPlanClarificationOnly(content)) return false;
  return (
    messageQualifiesForPlanPanel(content, msg)
    || (isRunning && msg.chatMode === "plan" && looksLikeStreamingPlanContent(content.trim()))
  );
}

/** User explicitly opened the plan panel — allow any non-empty Plan-mode answer. */
export function canForceOpenPlanPanel(
  content: string,
  msg: Pick<ChatMessage, "chatMode">,
): boolean {
  if (msg.chatMode !== "plan" || !content.trim()) return false;
  return !isPlanClarificationOnly(content);
}

export async function resolvePlanContentForDisplay(
  projectPath: string,
  msg: PlanMessageSource,
  displayedContent = "",
): Promise<string> {
  const inline = extractPlanContentFromStoredMessage(msg, displayedContent).trim();
  if (inline && messageQualifiesForPlanPanel(inline, msg)) return inline;
  if (msg.chatMode === "plan" && inline) return inline;
  const root = projectPath.trim();
  if (root && msg.planFilePath?.trim()) {
    const disk = await readPlanFile(root);
    if (disk.ok && disk.content?.trim()) return disk.content.trim();
  }
  return inline;
}
